name: Build and Test @storyblok-components monorepo packages

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Building packages
        env:
          NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
        run: |
          npm config set registry $NPM_REGISTRY
          npm config set //registry.npmjs.org/:_authToken $NPM_REGISTRY_TOKEN
          npm config set //registry.npmjs.org/:always-auth true
          yarn install

          yarn start
