name: Build and Publish @storyblok-components monorepo packages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Building packages
        env:
          NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
        run: |
          npm config set registry $NPM_REGISTRY
          npm config set //registry.npmjs.org/:_authToken $NPM_REGISTRY_TOKEN
          npm config set //registry.npmjs.org/:always-auth true
          yarn install

          yarn start
      - name: Prepare repository
        run: git reset --hard HEAD
      - name: Publishing on Global npm registry
        env:
          NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
          NO_HUSKY: 1
        run: |
          git config --global user.name 'storyblok-components'
          git config --global user.email 'marckraw@icloud.com'
          git log -n 1
          git status
          npx lerna publish --conventional-commits --changelog-preset conventionalcommits -m 'chore(release): publish' --registry $NPM_REGISTRY --yes
